services:
  iptv-stream-manager:
    container_name: iptv-stream-manager
    build: .
    restart: unless-stopped

    ports:
      - "8090:8080"

    volumes:
      - ./app.py:/app/app.py:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./channels_selected.yaml:/app/channels_selected.yaml:ro
      - ./secrets.yaml:/app/secrets.yaml:ro
