services:
  iptv-stream-manager:
    container_name: iptv-stream-manager
    image: python:3.13-slim
    restart: unless-stopped

    ports:
      - "8090:8080"

    command:
      - /bin/sh
      - -c
      - pip install --no-cache-dir aiohttp==3.12.15 pyyaml && exec python /app/app.py

    volumes:
      - ./:/app
