services:
  iptv-stream-manager:
    container_name: iptv-stream-manager
    image: ghcr.io/ciux23/iptv-stream-manager:latest
    restart: unless-stopped

    ports:
      - "8090:8080"

    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./channels_selected.yaml:/app/channels_selected.yaml:ro
      - ./secrets.yaml:/app/secrets.yaml:ro
